#!/bin/sh
'''exec' "/home/marc/Documents/Code/Spring Boot/dt.app.java/venv_automatisation/bin/python3" "$0" "$@"
' '''
import sys
from charset_normalizer.cli import cli_detect
if __name__ == '__main__':
    sys.argv[0] = sys.argv[0].removesuffix('.exe')
    sys.exit(cli_detect())
