
CREATE TABLE G2010R.DPW_LIGNEMARITIME (
	CODELIGNE VARCHAR (5) NOT NULL,
	NOMLIGNE VARCHAR (255) ,
	PRIMARY KEY (CODELIGNE)
);


CREATE TABLE G2010R.DPW_TRANSPORTEUR (
	CODETRANSPORTEUR VARCHAR (10) NOT NULL,
	NOMTRANSPORTEUR VARCHAR (255) ,
	PRIMARY KEY (CODETRANSPORTEUR)
);

CREATE TABLE G2010R.DPW_VOYAGENAVIRE (
	CODELIGNE VARCHAR (5) NOT NULL,
	NUMVOYAGE VARCHAR (50) NOT NULL,
	NOMNAVIRE VARCHAR (255) ,
	DATEESTIMATIONARRIVEE DATE    (4) ,
	DATEDEPART DATE    (4) ,
	PRIMARY KEY (CODELIGNE,NUMVOYAGE)
);

ALTER TABLE G2010R.DPW_VOYAGENAVIRE
	ADD FOREIGN KEY (CODELIGNE) 
	REFERENCES G2010R.DPW_LIGNEMARITIME (CODELIGNE);



CREATE TABLE G2010R.DPW_DEMANDETRANSPORTEUR (
	DECANNEEENREGDEC VARCHAR (4) NOT NULL,
	DECBURENREGDEC VARCHAR (3) NOT NULL,
	DECNUMDECLARATION INTEGER  NOT NULL,
	CODETRANSPORTEUR VARCHAR (10) NOT NULL,
	NUMVOYAGE VARCHAR (100) NOT NULL,
	NOMTRANSPORTEUR VARCHAR (255) ,
	PRIMARY KEY (CODETRANSPORTEUR,DECANNEEENREGDEC,DECBURENREGDEC,DECNUMDECLARATION,NUMVOYAGE)
);


CREATE TABLE G2010R.DPW_EMB_SEGGENDEC (
	DECANNEEENREGDEC VARCHAR (4) NOT NULL,
	DECBURENREGDEC VARCHAR (3) NOT NULL,
	DECNUMDECLARATION INTEGER  NOT NULL,
	DECDATEENREGDEMANDE TIMESTAMP ,
	DECDATEVALIDATIONDEMANDE TIMESTAMP ,
	DECREGDOUANIER CHAR    (2) ,
	CODELIGNE VARCHAR (5) NOT NULL,
	NOMNAVIRE VARCHAR (50) NOT NULL,
	NUMVOYAGE VARCHAR (100) NOT NULL,
	LIBELLE_PAYS_DEST VARCHAR (100) ,
	RCNINEA_DECL VARCHAR (50) ,
	RCNINEA_DEST VARCHAR (50) ,
	REF_BOOKING VARCHAR (100) NOT NULL,
	DECISION VARCHAR (10) ,
	DATEDECISION TIMESTMP(12) ,
	RCCODEUSER_DECISION VARCHAR (7) ,
	DOCEMPOTAGE BLOB    (4) ,
	DB2_GENERATED_ROWID_FOR_LOBS ROWID   (17) DEFAULT A NOT NULL,
	MOTIF_DECISION VARCHAR (255) ,
	PRIMARY KEY (DECANNEEENREGDEC,DECBURENREGDEC,DECNUMDECLARATION,NUMVOYAGE)
);


CREATE TABLE G2010R.DPW_EMB_SEGARTDEC (
	DECANNEEENREGDEC VARCHAR (4) NOT NULL,
	DECBURENREGDEC VARCHAR (3) NOT NULL,
	DECNUMDECLARATION INTEGER  NOT NULL,
	DECNUMARTDEC INTEGER  NOT NULL,
	NUMVOYAGE VARCHAR (100) NOT NULL,
	DECMODECOND VARCHAR (4) ,
	DECNUMTITRETRANS VARCHAR (35) ,
	RCLIBELLELIEUEMB VARCHAR (100) ,
	CODE_SH_PRODUIT VARCHAR (10) ,
	RCLIBELLETARIF VARCHAR (100) ,
	DECDESCOMMERCIALE VARCHAR (512) ,
	DECNBRECOLIS DECIMAL (15)  NOT NULL,
	DECPOIDSBRUTDEC DECIMAL (18,3)  NOT NULL,
	DECPDNETDEC DECIMAL (18,3)  NOT NULL,
	DECQTECOMPLEMENTAIRE DECIMAL (15) ,
	DECUNITECOMPLEMENTAIRE VARCHAR (3) ,
	DECREGIMEFISCAL CHAR    (2) ,
	PRIMARY KEY (DECANNEEENREGDEC,DECBURENREGDEC,DECNUMARTDEC,DECNUMDECLARATION,NUMVOYAGE)
);


CREATE TABLE G2010R.DPW_EMB_SEGCONTDEC (
	DECANNEEENREGDEC VARCHAR (4) NOT NULL,
	DECBURENREGDEC VARCHAR (3) NOT NULL,
	DECNUMDECLARATION INTEGER  NOT NULL,
	DECNUMARTDEC INTEGER  NOT NULL,
	DECNUMCONTENEUR VARCHAR (11) NOT NULL,
	DECTYPECONTENEUR VARCHAR (4) ,
	NUMVOYAGE VARCHAR (100) NOT NULL,
	DECTAILLECONTENEUR VARCHAR (8) ,
	DECNUMEROPLOMB VARCHAR (35) ,
	POIDSBRUT INTEGER ,
	POIDSNET INTEGER ,
	POIDSVGM INTEGER ,
	CONTENANCE VARCHAR (5) ,
	CODETRANSPORTEUR VARCHAR (10) ,
	STATUT VARCHAR (7) ,
	PORT_DESTINATION VARCHAR (5) ,
	PRIMARY KEY (DECANNEEENREGDEC,DECBURENREGDEC,DECNUMARTDEC,DECNUMCONTENEUR,DECNUMDECLARATION,NUMVOYAGE)
);


ALTER TABLE G2010R.DPW_EMB_SEGGENDEC
	ADD FOREIGN KEY (CODELIGNE) 
	REFERENCES G2010R.DPW_LIGNEMARITIME (CODELIGNE);

ALTER TABLE G2010R.DPW_EMB_SEGGENDEC
	ADD FOREIGN KEY (RCNINEA_DECL) 
	REFERENCES G2010R.NINEA (NUMERONINEA);

ALTER TABLE G2010R.DPW_EMB_SEGGENDEC
	ADD FOREIGN KEY (RCNINEA_DEST) 
	REFERENCES G2010R.NINEA (NUMERONINEA);
