CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NULL,
    user_name VARCHAR(255) NULL,
    user_email VARCHAR(255) NULL,
    user_role VARCHAR(100) NULL,
    method VARCHAR(10) NOT NULL,
    url VARCHAR(1000) NOT NULL,
    route_name VARCHAR(255) NULL,
    controller_action VARCHAR(255) NULL,
    ip_address VARCHAR(45) NULL,
    user_agent TEXT NULL,
    payload JSON NULL,
    query_params JSON NULL,
    session_id VARCHAR(255) NULL,
    response_status SMALLINT UNSIGNED NULL,
    duration_ms INT UNSIGNED NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_audit_logs_created_at (created_at),
    INDEX idx_audit_logs_user_id (user_id),
    INDEX idx_audit_logs_method (method),
    INDEX idx_audit_logs_response_status (response_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
